workflow fix

diff --git a/.github/workflows/quam_test.yaml b/.github/workflows/quam_test.yaml
--- a/.github/workflows/quam_test.yaml
+++ b/.github/workflows/quam_test.yaml
@@ -23,18 +23,35 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install .[dev]
-        
-    - name: Test with pytest
-      run: |
-        pip install pytest
-        pytest
 
     - name: Run pytest and generate a report
-    run: pytest --junitxml=pytest-report.xml
-  
-    - name: Upload pytest report as an artifact
-      if: success() || failure()
-      uses: actions/upload-artifact@v4
+      run: pytest --junitxml=pytest-report.xml
+
+    - name: Surface failing tests
+      if: always()
+      uses: pmeier/pytest-results-action@main
       with:
-        name: pytest-report-${{ matrix.python-version }}
-        path: pytest-report.xml
+        # A list of JUnit XML files, directories containing the former, and wildcard
+        # patterns to process.
+        # See @actions/glob for supported patterns.
+        path: test-results.xml
+
+        # (Optional) Add a summary of the results at the top of the report
+        summary: true
+
+        # (Optional) Select which results should be included in the report.
+        # Follows the same syntax as `pytest -r`
+        display-options: fEX
+
+        # (Optional) Fail the workflow if no JUnit XML was found.
+        fail-on-empty: true
+
+        # (Optional) Title of the test results section in the workflow summary
+        title: Test results
+  
+    # - name: Upload pytest report as an artifact
+    #   if: success() || failure()
+    #   uses: actions/upload-artifact@v4
+    #   with:
+    #     name: pytest-report-${{ matrix.python-version }}
+    #     path: pytest-report.xml
